### ISSUE TITLE
Order by clause 

### ISSUE THREAD

**Issue by catchsrinik** [mulesoft-labs/mql#2]
Order by clause not working , we need to fix OrderByComparator class.
Please see my posting here.
http://stackoverflow.com/questions/9424585/mule-query-language-order-by-clause.

I love to contribute to this project.

**Comment by catchsrinik** [comment]
fixed OrderByComparator class.

**Comment by dandiep** [comment]
Hiya, would love to receive some patches from you! You can either attach them to the github issue or send pull requests.

**Comment by catchsrinik** [comment]
Hi Dan,

Created and closed the pull request. I commited my code changes.

Thanks
Srini-

On Mon, Feb 27, 2012 at 3:27 PM, Dan Diephouse <
reply@reply.github.com

**Comment by catchsrinik** [comment]
done
